# -*- coding: utf-8 -*-
"""
Created on Mon Jan 30 11:54:58 2023

Load in & reformat FRAPPE Pandora data

@author: okorn
"""

#Import in necessary packages
from tkinter.filedialog import askdirectory
import os
import pandas as pd
import datetime

#Prompt user to select folder for analysis
path = askdirectory(title='Select Folder for analysis').replace("/","\\")

#Get the list of files from this directory
from os import listdir
from os.path import isfile, join
fileList = [f for f in listdir(path) if isfile(join(path, f))]

#create a datframe to hold our data from each file
data = pd.DataFrame()

#loop through each of the files & extract only the columns we need:
  #datetime, CO (dry)
  
#iterate over each file in the main folder
for i in range(len(fileList)-1):
    
    #Create full file path for reading file
    filePath = os.path.join(path, fileList[i])
    
    #load in the file
    temp = pd.read_csv(filePath,skiprows=76,sep=',',encoding = "ISO-8859-1",
                       usecols = [ '    Date-GMT','      NO2'])
    
    #if NO2, skiprows = 76
    #if O3, skiprows = 77
    
    #remove empty spaces in data for workability
    temp.columns = temp.columns.str.strip() 
    
    #correct the format of the datetimes
    temp['Date-GMT'] = temp['Date-GMT'].apply(lambda x: datetime.datetime.strptime(str(x), '%Y%m%d%H%M%S'))
    
    #Save this into our data dictionary
    data = data.append(temp)
    
    #get rid of any duplicate datetimes
    data = data.drop_duplicates()
    
    #make the datetime column the index
    data.index = data['Date-GMT']
    
    #retime to minutely
    data = data.resample('T').mean()
    
    #drop any NaNs generated by the resampling
    data = data.dropna()

#save out the final data
savePath = os.path.join(path,'Pandora.csv')
data.to_csv(savePath)